In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/housing.csv')

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
df.shape

(20640, 10)

In [ ]:
df['total_bedrooms'].unique()

array([ 129., 1106.,  190., ..., 3008., 1857., 1052.])

In [ ]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].mean())

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error

In [ ]:
le = LabelEncoder()
df["ocean_proximity"] = le.fit_transform(df["ocean_proximity"])

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,3

In [ ]:
X = df.drop("median_house_value", axis=1)

In [ ]:
y = df["median_house_value"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = DecisionTreeRegressor(random_state=42)

In [ ]:
model.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(y_pred[:10])

[ 65900.  52900. 500001. 289800. 378600. 162000. 296700. 149000. 178200.
 500001.]

In [ ]:
print("Score:", model.score(X_train, y_train))

Score: 1.0

In [ ]:
print("Score:", model.score(X_test, y_test))

Score: 0.6384055409436313

In [ ]:
from lightgbm import LGBMRegressor

In [ ]:
model = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

In [ ]:
model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000868 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1843
[LightGBM] [Info] Number of data points in the train set: 16512, number of used features: 9
[LightGBM] [Info] Start training from score 207194.693738

LGBMRegressor(random_state=42)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print("Predicted Values:")
print(y_pred[:10])

Predicted Values:
[ 61289.46966293  77258.60143427 449050.97198664 255781.03677865
 308748.95921278 157154.49695737 321252.65357066 211645.05406199
 324079.05299984 481362.74238051]

In [ ]:
print("R2 Score:", model.score(X_test, y_test))

R2 Score: 0.8233682203268838

In [35]:
longitude = float(input("Longitude: "))
latitude = float(input("Latitude: "))
housing_median_age = float(input("Housing Median Age: "))
total_rooms = int(input("Total Rooms: "))
total_bedrooms = int(input("Total Bedrooms: "))
population = float(input("Population: "))
households = int(input("Households: "))
median_income = float(input("Median Income: "))
ocean_proximity = int(input("Ocean Proximity: "))

new_house = pd.DataFrame({
    "longitude": [longitude],
    "latitude": [latitude],
    "housing_median_age": [housing_median_age],
    "total_rooms": [total_rooms],
    "total_bedrooms": [total_bedrooms],
    "population": [population],
    "households": [households],
    "median_income": [median_income],
    "ocean_proximity": [ocean_proximity]
})

prediction = model.predict(new_house)

print(f"\nPredicted House Price: ${prediction[0]:,.2f}")

Longitude: -122.23
Latitude: 37.86
Housing Median Age: 21
Total Rooms: 7099
Total Bedrooms: 1006
Population: 2401
Households: 1138
Median Income: 8.3014
Ocean Proximity: 3

Predicted House Price: $418,126.34